// Code generated by mockery v2.42.1. DO NOT EDIT.

package repository

import (
	context "context"

	models "github.com/storyofhis/books-management/httpserver/repository/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBookRepo is an autogenerated mock type for the BookRepo type
type MockBookRepo struct {
	mock.Mock
}

type MockBookRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookRepo) EXPECT() *MockBookRepo_Expecter {
	return &MockBookRepo_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function with given fields: ctx, book
func (_m *MockBookRepo) CreateBook(ctx context.Context, book *models.Book) error {
	ret := _m.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Book) error); ok {
		r0 = rf(ctx, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookRepo_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockBookRepo_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - book *models.Book
func (_e *MockBookRepo_Expecter) CreateBook(ctx interface{}, book interface{}) *MockBookRepo_CreateBook_Call {
	return &MockBookRepo_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, book)}
}

func (_c *MockBookRepo_CreateBook_Call) Run(run func(ctx context.Context, book *models.Book)) *MockBookRepo_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Book))
	})
	return _c
}

func (_c *MockBookRepo_CreateBook_Call) Return(_a0 error) *MockBookRepo_CreateBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookRepo_CreateBook_Call) RunAndReturn(run func(context.Context, *models.Book) error) *MockBookRepo_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBook provides a mock function with given fields: ctx, id
func (_m *MockBookRepo) DeleteBook(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookRepo_DeleteBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBook'
type MockBookRepo_DeleteBook_Call struct {
	*mock.Call
}

// DeleteBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookRepo_Expecter) DeleteBook(ctx interface{}, id interface{}) *MockBookRepo_DeleteBook_Call {
	return &MockBookRepo_DeleteBook_Call{Call: _e.mock.On("DeleteBook", ctx, id)}
}

func (_c *MockBookRepo_DeleteBook_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookRepo_DeleteBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookRepo_DeleteBook_Call) Return(_a0 error) *MockBookRepo_DeleteBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookRepo_DeleteBook_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockBookRepo_DeleteBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookById provides a mock function with given fields: ctx, id
func (_m *MockBookRepo) GetBookById(ctx context.Context, id uuid.UUID) (*models.Book, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookById")
	}

	var r0 *models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Book, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Book); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookRepo_GetBookById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookById'
type MockBookRepo_GetBookById_Call struct {
	*mock.Call
}

// GetBookById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockBookRepo_Expecter) GetBookById(ctx interface{}, id interface{}) *MockBookRepo_GetBookById_Call {
	return &MockBookRepo_GetBookById_Call{Call: _e.mock.On("GetBookById", ctx, id)}
}

func (_c *MockBookRepo_GetBookById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockBookRepo_GetBookById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookRepo_GetBookById_Call) Return(_a0 *models.Book, _a1 error) *MockBookRepo_GetBookById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookRepo_GetBookById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Book, error)) *MockBookRepo_GetBookById_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooks provides a mock function with given fields: ctx
func (_m *MockBookRepo) GetBooks(ctx context.Context) ([]*models.Book, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []*models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Book, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Book); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookRepo_GetBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooks'
type MockBookRepo_GetBooks_Call struct {
	*mock.Call
}

// GetBooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBookRepo_Expecter) GetBooks(ctx interface{}) *MockBookRepo_GetBooks_Call {
	return &MockBookRepo_GetBooks_Call{Call: _e.mock.On("GetBooks", ctx)}
}

func (_c *MockBookRepo_GetBooks_Call) Run(run func(ctx context.Context)) *MockBookRepo_GetBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBookRepo_GetBooks_Call) Return(_a0 []*models.Book, _a1 error) *MockBookRepo_GetBooks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookRepo_GetBooks_Call) RunAndReturn(run func(context.Context) ([]*models.Book, error)) *MockBookRepo_GetBooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function with given fields: ctx, book, id
func (_m *MockBookRepo) UpdateBook(ctx context.Context, book *models.Book, id uuid.UUID) error {
	ret := _m.Called(ctx, book, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Book, uuid.UUID) error); ok {
		r0 = rf(ctx, book, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookRepo_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockBookRepo_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - book *models.Book
//   - id uuid.UUID
func (_e *MockBookRepo_Expecter) UpdateBook(ctx interface{}, book interface{}, id interface{}) *MockBookRepo_UpdateBook_Call {
	return &MockBookRepo_UpdateBook_Call{Call: _e.mock.On("UpdateBook", ctx, book, id)}
}

func (_c *MockBookRepo_UpdateBook_Call) Run(run func(ctx context.Context, book *models.Book, id uuid.UUID)) *MockBookRepo_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Book), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockBookRepo_UpdateBook_Call) Return(_a0 error) *MockBookRepo_UpdateBook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookRepo_UpdateBook_Call) RunAndReturn(run func(context.Context, *models.Book, uuid.UUID) error) *MockBookRepo_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookRepo creates a new instance of MockBookRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookRepo {
	mock := &MockBookRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
